package com.worldexplorerblog.kotlinstrava.models

data class AthleteDetailed(val id: Int,
                           val firstName: String,
                           val lastName: String,
                           val profileMedium: String,
                           val profile: String,
                           val city: String,
                           val state: String,
                           val country: String,
                           val sex: String,
                           val friend: String?,
                           val follower: String?,
                           val premium: Boolean,
                           val createdAt: String,
                           val updatedAt: String,
                           val followerCount: Int,
                           val friendCount: Int,
                           val mutualFriendCount: Int,
                           val athleteType: Int,
                           val datePreference: String,
                           val measurementPreference: String,
                           val email: String,
                           val ftp: Int?,
                           val weight: Float?,
                           val clubs: List<ClubSummary>,
                           val bikes: List<GearSummary>,
                           val shoes: List<GearSummary>)

